---
# tasks file for switch-apt-mirror.ansible.role

- name: replace apt mirror on ubuntu
  become: true
  template:
    src: templates/sources.list.ubuntu.j2
    dest: /etc/apt/sources.list
    backup: yes
  register: replace_apt_config
  when: ansible_distribution|lower == 'ubuntu'

- name: replace apt mirror on debian
  become: yes
  template:
    src: templates/sources.list.debian.j2
    dest: /etc/apt/sources.list
    backup: yes
  register: replace_apt_config
  when: ansible_distribution|lower == 'debian'

- name: print replace_apt_config
  debug:
    var: replace_apt_config

- name: update apt cache
  become: true
  apt:
    update_cache: yes

# vim: ft=ansible :
