---
# tasks file for switch-apt-mirror-to-taiwan.ansible.role

- name: replace apt mirror on ubuntu
  become: yes
  template: >
    src=templates/sources.list.ubuntu.j2
    dest=/etc/apt/sources.list
    backup=yes
  when: ansible_distribution|lower == "ubuntu"
  notify: update apt cache

- name: replace apt mirror on debian
  become: yes
  template: >
    src=templates/sources.list.debian.j2
    dest=/etc/apt/sources.list
    backup=yes
  when: ansible_distribution|lower == "debian"
  notify: update apt cache

# vim: ft=ansible :
