---
# tasks file for switch-apt-mirror.ansible.role

- name: replace apt mirror on ubuntu
  become: yes
  template: >
    src=templates/sources.list.ubuntu.j2
    dest=/etc/apt/sources.list
    backup=yes
  when: ansible_distribution|lower == "ubuntu"

- name: replace apt mirror on debian
  become: yes
  template: >
    src=templates/sources.list.debian.j2
    dest=/etc/apt/sources.list
    backup=yes
  when: ansible_distribution|lower == "debian"

- name: update apt cache
  become: yes
  apt: update_cache=yes

# vim: ft=ansible :
