---
# tasks file for switch-apt-mirror.ansible.role

- name: ubuntu
  block:

    - name: replace apt mirror on ubuntu
      become: true
      template:
        src: templates/sources.list.ubuntu.j2
        dest: /etc/apt/sources.list
        backup: yes
      register: replace_ubuntu_apt_config

    - name: update apt cache on ubuntu
      become: true
      apt:
        update_cache: yes
      when: replace_ubuntu_apt_config.changed

  when: ansible_distribution|lower == 'ubuntu'

- name: debian
  block:

    - name: replace apt mirror on debian
      become: true
      template:
        src: templates/sources.list.debian.j2
        dest: /etc/apt/sources.list
        backup: yes
      register: replace_debian_apt_config

    - name: update apt cache on debian
      become: true
      apt:
        update_cache: yes
      when: replace_debian_apt_config.changed

  when: ansible_distribution|lower == 'debian'

# vim: ft=yaml.ansible :
